---
- name: Run commands on Linux nodes
  hosts: linux_vms
  become: yes
  roles:
    - users

  tasks:
    - name: Test #1 - Run df -h command
      command: df -h
      register: df_output
      changed_when: false

    - name: Display df -h output
      debug:
        var: df_output.stdout_lines

    - name: Test #2 - Run sudo tail /etc/profile command
      command: sudo tail /etc/profile
      register: tail_output
      changed_when: false

    - name: Display tail /etc/profile output
      debug:
        var: tail_output.stdout_lines
