---
- name: Add cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Add user accounts
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - user1000
    - user2000

- name: Distribute SSH keys for users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '~/' + item + '/.ssh/id_rsa.pub') }}"
  loop:
    - user1000
    - user2000
