---
- name: Add cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Add user accounts
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - user1000
    - user2000
  register: user_result

- name: Distribute SSH keys for users
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_public_key }}"
  loop: "{{ user_result.results }}"

# Add the task to configure passwordless sudo for the cloudadmins group
- name: Configure passwordless sudo for cloudadmins group
  lineinfile:
    path: /etc/sudoers
    line: '%cloudadmins ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'